<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUmQzxkV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUmQzxkV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUmQzxkV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUmQzxkV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUmQzxkV\App_KernelDevDebugContainer([
    'container.build_hash' => 'UmQzxkV',
    'container.build_id' => '9026edac',
    'container.build_time' => 1652639365,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUmQzxkV');
